"""empty message

Revision ID: 1d75ac0d2ebf
Revises: 4ced0c7597d9
Create Date: 2024-05-09 15:16:29.242829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d75ac0d2ebf'
down_revision = '4ced0c7597d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('climate')
        batch_op.drop_column('terrain')
        batch_op.drop_column('population')

    op.create_table('character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='character_pkey')
    )
    # ### end Alembic commands ###
